name: .NET Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  welcome:
    name: Welcome Message
    runs-on: ubuntu-latest
    steps:
      - name: Print Welcome Message
        run: echo "Welcome to the .NET Workflow!"

  build:
    needs: welcome
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore
        
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults"

      - name: Upload dotnet test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results
          path: TestResults
